version: "3"
services:
  
  backend:
    container_name: backend
    build: ./backend/build/golang
    tty: true
    ports:
      - "8000:8000"
    working_dir: /go/src/y_ara/english-words/backend
    volumes:
      - ./backend:/go/src/y_ara/english-words/backend
    command: go run cmd/main.go

  db:
    container_name: db
    image: postgres:12.2
    env_file: 
      - ./backend/config/.env.local
    volumes: 
      - ./backend/build/postgres/strage:/var/lib/postgresql
      - ./backend/build/postgres/sql:/docker-entrypoint-initdb.d
    ports: 
      - 5432:5432

  frontend:
    container_name: frontend
    build: ./docker
    ports: 
      - '8080:8080'
    volumes: 
      - ./frontend:/app
    tty: true
    stdin_open: true
    command: /bin/sh

